BDRC Abstract Work ID: W19740
BDRC Digital Edition ID: W0OP000001
BDRC Paper Edition ID: 

Digital Publication Source:
 - Organization:
 - Website:
 - Acquisition Date:
 - Parser: <link>

Crawled Metadata:
 - Title Variants:
   - Web Page Title:
     - bo:
     - en:
 - Category:
    - bo:
    - en:
 - Collection:
    - bo:
    - en:
 - Publisher:
    - bo:
    - en:
 - SKU:

Digital Publication Metadata:
 - Title Variants:
   - Book Title:
   - Vol Number:
 - Author:
 - Publisher:
 - Year:
 - ISBN:

# Imported with BDRC's API
BDRC Bibliographic Information:
  - Title Variants:
    - Bibliographical Title: spyod 'jug
    - Title Page Title: byang chub sems dpa'i spyod pa la 'jug pa/
    - Other Title: bodhicaryavatara
  - Catalog Information: Collected Works by renowned Mongolian master Damtsik Dorje from Urga.
  - Archive Information:
    - Number of Volumes	21
    - Status: scanned
    - License: Public Domain
    - Access: Open Access.
    - Status: released
  - Product Information: All Released and Unrestricted Works
  - Notes: 
  - External Hyperlink: No search results

BDRC Publication Information:
  - Publisher Name: nub byang mi rigs slob grwa chen mo
  - Publisher Location: [lan kru'u]
  - Publisher Date: [200?]
  - Encoding: In Tibetan
  - Extent: 21 v.
  - hollis: 014261004
  - TBRC Holdings: 1
